#!/bin/bash
#
# functions - puppet-openstack_spec_helper specific functions
#

install_gems() {
  mkdir .bundled_gems
  export GEM_HOME=`pwd`/.bundled_gems

  # use puppet-nova to test the gem
  if [ -e /usr/zuul-env/bin/zuul-cloner ] ; then
      /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
          https://opendev.org openstack/puppet-nova
  else
      git clone https://opendev.org/openstack/puppet-nova openstack/puppet-nova
  fi
  cd openstack/puppet-nova

  # Modify Gemfile to use local library and not the one on git
  # so we can actually test the current state of the gem.
  sed -i -e "s|\('puppet-openstack_spec_helper',.*\) \(:git\).*|\1 :path => '../..'|g" Gemfile
  # NOTE(aschultz): in order for this to work we need to nuke the branch line
  # since we're replacing the repository with a path
  sed -i "/.*ref[[:space:]]*=> 'stable\/.*/d" Gemfile

  # Install dependencies
  ruby <<EOF
cmd = 'gem install bundler --no-rdoc --no-ri --verbose'
if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0') then
  cmd += ' -v 1.17.3'
end
system(cmd)
EOF
  $GEM_HOME/bin/bundle install
}
