#!/bin/bash
#
# functions - puppet-openstack_spec_helper specific functions
#

install_gems() {
  mkdir .bundled_gems
  export GEM_HOME=`pwd`/.bundled_gems

  # use puppet-nova to test the gem
  if [ -e /usr/zuul-env/bin/zuul-cloner ] ; then
      /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
          git://git.openstack.org openstack/puppet-nova
  else
      git clone git://git.openstack.org/openstack/puppet-nova -b stable/queens openstack/puppet-nova
  fi
  cd openstack/puppet-nova

  # Modify Gemfile to use local library and not the one on git
  # so we can actually test the current state of the gem.
  sed -i -e "s|\('puppet-openstack_spec_helper',.*\) \(:git\).*|\1 :path => '../..'|g" Gemfile
  # NOTE(aschultz): in order for this to work we need to nuke the branch line
  # since we're replacing the repository with a path
  sed -i "/.*ref[[:space:]]*=> 'stable\/.*/d" Gemfile

  # Install dependencies
  gem install bundler --no-rdoc --no-ri --verbose
  $GEM_HOME/bin/bundle install
}
